config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :reqs
  resources :recruiters
  resources :employers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#index'
end

app/models/employer.rb
class Employer < ApplicationRecord
  has_many :reqs
  has_many :reviews, as: :reviewable
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: [:show, :edit, :update, :destroy]

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.all
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to @employer, notice: 'Employer was successfully created.' }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'Employer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:name, :industry, :certified, :notes)
    end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<%= form_for(employer) do |f| %>
  <% if employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% employer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col col-1 field">
      <%= f.label :name %>
    </div>
    <div class="col">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row">
    <div class="col col-1 field">
      <%= f.label :industry %>
    </div>
    <div class="col">
      <%= f.text_field :industry %>
    </div>
  </div>

  <div class="row">
    <div class="col col-1 field">
      <%= f.label :certified %>
    </div>
    <div class="col">
      <%= f.check_box :certified %>
    </div>
  </div>

  <div class="row">
    <div class="col col-1 field">
      <%= f.label :notes %>
    </div>
    <div class="col">
      <%= f.text_area :notes %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/employers/edit.html.erb
<h1>Editing Employer</h1>

<%= render 'form', employer: @employer %>

<%= link_to 'Back', employer_path(@employer) %>

app/views/employers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employers</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Industry</th>
      <th>Certified</th>
      <th>Notes</th>
    </tr>
  </thead>

  <tbody>
    <% @employers.each do |employer| %>
      <tr>
        <td><%= link_to employer.name, employer %></td>
        <td><%= employer.industry %></td>
        <td><%= employer.certified %></td>
        <td><%= employer.notes %></td>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employer', new_employer_path, class: 'btn btn-primary' %>

app/views/employers/new.html.erb
<h1>New Employer</h1>

<%= render 'form', employer: @employer %>

<%= link_to 'Back', employers_path %>

app/views/employers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1 class="text-center"><strong><%= @employer.name %></strong></h1>
</p>

<p>
  <strong>Industry:</strong>
  <%= @employer.industry %>
</p>

<p>
  <strong>Certified:</strong>
  <%= @employer.certified %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @employer.notes %>
</p>

<%= link_to 'Edit', edit_employer_path(@employer), class: 'btn-secondary btn-sm' %>

<hr class="section-divider">
<p/>
  <h2><strong>Reqs</strong></h2>
  <table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Date Created</th>
    </tr>
  </thead>

  <tbody>
    <% @employer.reqs.each do |req|%>
      <tr>
        <td><%= link_to req.title, req_path(req) %></td>
        <td><%= req.created_at.strftime('%B %d, %Y') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Create req', new_req_path(employer_id: @employer), class: 'btn btn-primary' %>

<hr class="section-divider">
<p/>
  <h2><strong>Reviews</strong></h2>
  <table class="table">
  <thead>
    <tr>
      <th>Text</th>
      <th>Date Created</th>
    </tr>
  </thead>

  <tbody>
    <% @employer.reviews.each do |rev|%>
      <tr>
        <td><%= link_to rev.text, review_path(rev) %></td>
        <td><%= rev.created_at.strftime('%B %d, %Y') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Create review', new_review_path(reviewee: @employer, reviewable_type: 'employer'), class: 'btn btn-primary' %>