config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :reqs
  resources :recruiters
  resources :employers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#index'
end

app/models/req.rb
class Req < ApplicationRecord
  belongs_to :employer
end

app/controllers/reqs_controller.rb
class ReqsController < ApplicationController
  before_action :set_req, only: [:show, :edit, :update, :destroy]

  # GET /reqs
  # GET /reqs.json
  def index
    @reqs = Req.all
  end

  # GET /reqs/1
  # GET /reqs/1.json
  def show
  end

  # GET /reqs/new
  def new
    @req = Req.new
  end

  # GET /reqs/1/edit
  def edit
  end

  # POST /reqs
  # POST /reqs.json
  def create
    @req = Req.new(req_params)

    respond_to do |format|
      if @req.save
        format.html { redirect_to @req.employer, notice: 'Req was successfully created.' }
        format.json { render :show, status: :created, location: @req }
      else
        format.html { render :new }
        format.json { render json: @req.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reqs/1
  # PATCH/PUT /reqs/1.json
  def update
    respond_to do |format|
      if @req.update(req_params.except(:employer_id))
        format.html { redirect_to @req.employer, notice: 'Req was successfully updated.' }
        format.json { render :show, status: :ok, location: @req }
      else
        format.html { render :edit }
        format.json { render json: @req.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reqs/1
  # DELETE /reqs/1.json
  def destroy
    @req.destroy
    respond_to do |format|
      format.html { redirect_to reqs_url, notice: 'Req was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_req
      @req = Req.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def req_params
      params.require(:req).permit(:title, :description, :employer_id)
    end
end

app/helpers/reqs_helper.rb
module ReqsHelper
end

app/views/reqs/_form.html.erb
<%= form_for(req) do |f| %>
  <% if req.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(req.errors.count, "error") %> prohibited this req from being saved:</h2>

      <ul>
      <% req.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col col-1 field">
      <%= f.label :title %>
    </div>
    <div class="col">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="row">
    <div class="col col-1 field">
      <%= f.label :description %>
    </div>
    <div class="col">
      <%= f.text_area :description %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>

  <%= f.hidden_field :employer_id, value: params[:employer_id] %>
<% end %>

app/views/reqs/edit.html.erb
<h1>Editing Req</h1>

<%= render 'form', req: @req %>

<%= link_to 'Back', reqs_path %>

app/views/reqs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reqs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @reqs.each do |req| %>
      <tr>
        <td><%= link_to req.title, req %></td>
        <td><%= req.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Req', new_req_path, class: 'btn btn-primary' %>

app/views/reqs/new.html.erb
<h1>New Req</h1>

<%= render 'form', req: @req %>

<%= link_to 'Back', employer_path(params[:employer_id]) %>

app/views/reqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @req.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @req.description %>
</p>

<%= link_to 'Edit', edit_req_path(@req), class: 'btn-primary btn-sm' %>
<%= link_to 'Back', employer_path(@req.employer), class: 'btn-primary btn-sm' %>