config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :reqs
  resources :recruiters
  resources :employers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#index'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.reviewable =
      if (review_params[:reviewable_type] == 'employer')
        Employer.find review_params[:reviewee]
      elsif (review_params[:reviewable_type] == 'recruiter')
        Recruiter.find review_params[:reviewee]
      end

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review.reviewable, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review.reviewable, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:reviewer, :reviewee, :reviewable_type, :text)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(review) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col col-1 field">
    <%= f.label :reviewer %>
    </div>
    <div class="col">
      <%= f.text_field :reviewer %>
    </div>
  </div>

  <div class="row">
    <div class="col col-1 field">
      <%= f.label :text %>
    </div>
    <div class="col">
      <%= f.text_field :text %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>

  <%= f.hidden_field :reviewee, value: params[:reviewee] %>
  <%= f.hidden_field :reviewable_type, value: params[:reviewable_type] %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table class="table">
  <thead>
    <tr>
      <th>Reviewer</th>
      <th>Reviewee</th>
      <th>Text</th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.reviewer %></td>
        <td><%= review.reviewee %></td>
        <td><%= review.text %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', params[:reviewable_type] == 'employer' ? employer_path(params[:reviewee]) : recruiter_path(params[:reviewee]) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @review.text %>
</p>

<hr class="section-divider">

<p><small>
  Review of
  <% if @review.reviewable_type == 'Employer' %>
    <%= Employer.find(@review.reviewee).name %>
  <% elsif @review.reviewable_type == 'Recruiter' %>
    <%= Recruiter.find(@review.reviewee).name %>
  <% end %>
  by <%= @review.reviewer %>
</small></p>