config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :reqs
  resources :recruiters
  resources :employers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#index'
end

app/models/recruiter.rb
class Recruiter < ApplicationRecord
  has_many :reviews, as: :reviewable
end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
  before_action :set_recruiter, only: [:show, :edit, :update, :destroy]

  # GET /recruiters
  # GET /recruiters.json
  def index
    @recruiters = Recruiter.all
  end

  # GET /recruiters/1
  # GET /recruiters/1.json
  def show
  end

  # GET /recruiters/new
  def new
    @recruiter = Recruiter.new
  end

  # GET /recruiters/1/edit
  def edit
  end

  # POST /recruiters
  # POST /recruiters.json
  def create
    @recruiter = Recruiter.new(recruiter_params)

    respond_to do |format|
      if @recruiter.save
        format.html { redirect_to @recruiter, notice: 'Recruiter was successfully created.' }
        format.json { render :show, status: :created, location: @recruiter }
      else
        format.html { render :new }
        format.json { render json: @recruiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recruiters/1
  # PATCH/PUT /recruiters/1.json
  def update
    respond_to do |format|
      if @recruiter.update(recruiter_params)
        format.html { redirect_to @recruiter, notice: 'Recruiter was successfully updated.' }
        format.json { render :show, status: :ok, location: @recruiter }
      else
        format.html { render :edit }
        format.json { render json: @recruiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recruiters/1
  # DELETE /recruiters/1.json
  def destroy
    @recruiter.destroy
    respond_to do |format|
      format.html { redirect_to recruiters_url, notice: 'Recruiter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recruiter
      @recruiter = Recruiter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recruiter_params
      params.require(:recruiter).permit(:name, :certified, :notes)
    end
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/views/recruiters/_form.html.erb
<%= form_for(recruiter) do |f| %>
  <% if recruiter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recruiter.errors.count, "error") %> prohibited this recruiter from being saved:</h2>

      <ul>
      <% recruiter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col col-1 field">
    <%= f.label :name %>
    </div>
    <div class="col">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row">
    <div class="col col-1 field">
      <%= f.label :certified %>
    </div>
    <div class="col">
      <%= f.check_box :certified %>
    </div>
  </div>

  <div class="row">
    <div class="col col-1 field">
      <%= f.label :notes %>
    </div>
    <div class="col">
      <%= f.text_area :notes %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/recruiters/edit.html.erb
<h1>Editing Recruiter</h1>

<%= render 'form', recruiter: @recruiter %>

<%= link_to 'Back', recruiters_path %>

app/views/recruiters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recruiters</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Certified</th>
      <th>Notes</th>
    </tr>
  </thead>

  <tbody>
    <% @recruiters.each do |recruiter| %>
      <tr>
        <td><%= link_to recruiter.name, recruiter %></td>
        <td><%= recruiter.certified %></td>
        <td><%= recruiter.notes %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recruiter', new_recruiter_path, class: 'btn btn-primary' %>

app/views/recruiters/new.html.erb
<h1>New Recruiter</h1>

<%= render 'form', recruiter: @recruiter %>

<%= link_to 'Back', recruiters_path %>

app/views/recruiters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1 class="text-center"><strong><%= @recruiter.name %></strong></h1>
</p>

<p>
  <strong>Certified:</strong>
  <%= @recruiter.certified %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @recruiter.notes %>
</p>

<%= link_to 'Edit', edit_recruiter_path(@recruiter), class: 'btn-secondary btn-sm' %>

<hr class="section-divider">
<p/>
  <h2><strong>Reviews</strong></h2>
  <table class="table">
  <thead>
    <tr>
      <th>Text</th>
      <th>Date Created</th>
    </tr>
  </thead>

  <tbody>
    <% @recruiter.reviews.each do |rev|%>
      <tr>
        <td><%= link_to rev.text, review_path(rev) %></td>
        <td><%= rev.created_at.strftime('%B %d, %Y') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Create review', new_review_path(reviewee: @recruiter, reviewable_type: 'recruiter'), class: 'btn btn-primary' %>